exp_name: Trial
save_path: /home/senthil/results
train_params:
  epochs: 100
  batch_size: 256
  lr: 0.001
  optimizer: Adam

model_params:
  model_name: MainNet
  extractor_op_features: 1000
  init: 0

